# Generated by Django 5.0.1 on 2024-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product description', max_length=200),
            preserve_default=False,
        ),
    ]
